name: Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set job timeout to 30 minutes
    steps:
      - name: Build and Deploy
        run: |
          # Checkout code using actions/checkout@v4
          git clone https://github.com/${{ github.repository }} .
          git checkout main
          # Set up Python
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt frozen-flask
          # Create db directory
          mkdir -p db
          touch db/blog.db
          ls -la
          pwd
          # Generate static files
          python freeze.py
          # Deploy to GitHub Pages
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv static/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          FLASK_ENV: production
          GIT_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}